// ================================================================
// AfiCare MediLink — PWD Rule Engine
//
// Architecture:
//   Each recommendation has a unique [id].
//   Right now every recommendation is produced by a hard-coded rule
//   (isRuleBased == true).
//
//   When real patient data accumulates, replace individual rules
//   with ML model predictions — one rule at a time — without
//   changing anything else in the codebase:
//
//     Future<List<PwdRecommendation>> getRecommendations(profile) async {
//       final mlResults = await _mlService.predict(profile);
//       return _rules.map((rule) {
//         final mlPred = mlResults[rule.id];
//         // If ML is confident enough, use ML; otherwise fall back to rule
//         if (mlPred != null && mlPred.confidence >= 0.75) return mlPred;
//         return rule;
//       }).toList();
//     }
//
// ================================================================

import '../models/disability_profile.dart';

// ----------------------------------------------------------------
// Recommendation categories
// ----------------------------------------------------------------

enum RecommendationPriority {
  /// Act immediately — safety risk
  critical,
  /// Act at this visit
  high,
  /// Act this month
  medium,
  /// General monitoring
  low,
}

enum RecommendationCategory {
  healthCheck,    // Screening / physical examination
  labTest,        // Blood, urine, imaging
  medication,     // Medication management
  referral,       // Specialist referral
  lifestyle,      // Daily living, devices, habits
  providerNote,   // Instruction for the treating clinician
  caregiverAlert, // Alert/task for the caregiver
}

// ----------------------------------------------------------------
// Recommendation data class
// ----------------------------------------------------------------

class PwdRecommendation {
  /// Stable unique identifier — this is the key for future ML swap.
  /// Convention: '{disabilityType}_{short_name}'
  final String id;

  final String title;
  final String description;
  final RecommendationPriority priority;
  final RecommendationCategory category;
  final DisabilityType triggerType;

  /// true  → generated by a hard-coded rule (current behaviour)
  /// false → generated by an ML model (future)
  final bool isRuleBased;

  /// Optional label for an action button, e.g. 'Book appointment'
  final String? actionLabel;

  // Future ML fields (uncomment when ML is ready):
  // final double? mlConfidence;
  // final String? mlModelVersion;

  const PwdRecommendation({
    required this.id,
    required this.title,
    required this.description,
    required this.priority,
    required this.category,
    required this.triggerType,
    this.isRuleBased = true,
    this.actionLabel,
  });
}

// ----------------------------------------------------------------
// Rule Engine
// ----------------------------------------------------------------

class PwdRuleEngine {
  const PwdRuleEngine();

  // ----------------------------------------------------------
  // Public API
  // ----------------------------------------------------------

  /// Returns all applicable recommendations for [profile],
  /// de-duplicated and sorted by priority (critical → low).
  ///
  /// Severity modifier:
  ///   mild     → critical + high only
  ///   moderate → critical + high + medium
  ///   severe   → all (critical + high + medium + low)
  List<PwdRecommendation> getRecommendations(DisabilityProfile profile) {
    if (profile.isEmpty) return [];

    final seen = <String>{};
    final results = <PwdRecommendation>[];

    for (final type in profile.disabilityTypes) {
      for (final rec in _rulesFor(type, profile)) {
        if (seen.add(rec.id)) {
          results.add(rec);
        }
      }
    }

    // Apply severity filter
    final filtered = results.where((r) {
      switch (profile.severity) {
        case DisabilitySeverity.mild:
          return r.priority == RecommendationPriority.critical ||
              r.priority == RecommendationPriority.high;
        case DisabilitySeverity.moderate:
          return r.priority != RecommendationPriority.low;
        case DisabilitySeverity.severe:
          return true;
      }
    }).toList();

    // Sort: critical first, then high, medium, low
    filtered.sort((a, b) => a.priority.index.compareTo(b.priority.index));
    return filtered;
  }

  /// Returns provider-facing notes only — used inside consultation screen.
  List<PwdRecommendation> getProviderNotes(DisabilityProfile profile) =>
      getRecommendations(profile)
          .where((r) =>
              r.category == RecommendationCategory.providerNote ||
              r.category == RecommendationCategory.caregiverAlert)
          .toList();

  /// Returns recommended specialist referrals for [profile].
  List<String> getSuggestedReferrals(DisabilityProfile profile) =>
      getRecommendations(profile)
          .where((r) => r.category == RecommendationCategory.referral)
          .map((r) => r.title)
          .toSet()
          .toList();

  // ----------------------------------------------------------
  // Internal — rules per disability type
  // ----------------------------------------------------------

  List<PwdRecommendation> _rulesFor(
    DisabilityType type,
    DisabilityProfile profile,
  ) {
    switch (type) {
      case DisabilityType.visual:
        return _visualRules(profile);
      case DisabilityType.hearing:
        return _hearingRules(profile);
      case DisabilityType.mobility:
        return _mobilityRules(profile);
      case DisabilityType.cognitive:
        return _cognitiveRules(profile);
      case DisabilityType.speech:
        return _speechRules(profile);
      case DisabilityType.chronicIllness:
        return _chronicIllnessRules(profile);
      case DisabilityType.mentalHealth:
        return _mentalHealthRules(profile);
      case DisabilityType.multiple:
        // For 'multiple', run rules for all common combinations
        return [
          ..._visualRules(profile),
          ..._mobilityRules(profile),
          ..._cognitiveRules(profile),
        ];
    }
  }

  // ----------------------------------------------------------
  // Visual impairment rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _visualRules(DisabilityProfile profile) => [
        const PwdRecommendation(
          id:          'visual_eye_pressure',
          title:       'Annual Eye Pressure Check',
          description: 'Intraocular pressure measurement to screen for '
              'glaucoma. Recommended annually for all patients with '
              'visual impairment.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.visual,
          actionLabel: 'Schedule with ophthalmologist',
        ),
        const PwdRecommendation(
          id:          'visual_fundus_exam',
          title:       'Retinal / Fundus Examination',
          description: 'Annual fundus photography or dilated eye exam to '
              'detect retinal disease, diabetic retinopathy, or macular '
              'degeneration early.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.visual,
          actionLabel: 'Schedule with ophthalmologist',
        ),
        const PwdRecommendation(
          id:          'visual_vitamin_a',
          title:       'Vitamin A Level Assessment',
          description: 'Vitamin A deficiency is a leading cause of '
              'preventable blindness in low-resource settings. '
              'Assess and supplement as needed.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.labTest,
          triggerType: DisabilityType.visual,
        ),
        const PwdRecommendation(
          id:          'visual_bp_monitoring',
          title:       'Blood Pressure Monitoring',
          description: 'Hypertension is a risk factor for hypertensive '
              'retinopathy and further vision loss. Monitor at every visit.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.visual,
        ),
        const PwdRecommendation(
          id:          'visual_ophthalmologist_referral',
          title:       'Ophthalmologist Referral',
          description: 'Refer to ophthalmologist for comprehensive eye '
              'assessment and low-vision rehabilitation services.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.referral,
          triggerType: DisabilityType.visual,
        ),
        const PwdRecommendation(
          id:          'visual_provider_note',
          title:       'Provider Note: Communication Adjustment',
          description: 'Patient has a visual impairment. Use verbal '
              'explanations, audio instructions, or large-print materials. '
              'Guide the patient to the examination table. '
              'Do not rely on written consent forms alone — read aloud.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.providerNote,
          triggerType: DisabilityType.visual,
        ),
        const PwdRecommendation(
          id:          'visual_orientation_mobility',
          title:       'Orientation & Mobility Training',
          description: 'Refer to orientation and mobility specialist to '
              'help patient navigate environments safely.',
          priority:    RecommendationPriority.low,
          category:    RecommendationCategory.referral,
          triggerType: DisabilityType.visual,
        ),
      ];

  // ----------------------------------------------------------
  // Hearing impairment rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _hearingRules(DisabilityProfile profile) => [
        const PwdRecommendation(
          id:          'hearing_audiometry',
          title:       'Annual Audiometry Review',
          description: 'Pure-tone audiometry to track hearing loss '
              'progression and assess need for device adjustment.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.hearing,
          actionLabel: 'Schedule audiometry',
        ),
        const PwdRecommendation(
          id:          'hearing_ear_health',
          title:       'Ear Health Check',
          description: 'Examine for cerumen (wax) impaction, otitis media, '
              'or infection — common causes of additional hearing loss that '
              'are easily treated.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.hearing,
        ),
        const PwdRecommendation(
          id:          'hearing_device_check',
          title:       'Hearing Aid / Device Maintenance',
          description: 'Confirm hearing aid is functioning, batteries are '
              'current, and the patient knows how to maintain the device. '
              'Refer to audiologist if device needs adjustment.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.lifestyle,
          triggerType: DisabilityType.hearing,
        ),
        const PwdRecommendation(
          id:          'hearing_mental_health',
          title:       'Mental Health Screening',
          description: 'Hearing loss is strongly associated with social '
              'isolation and depression. Screen using PHQ-9 at least once '
              'per year.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.hearing,
        ),
        const PwdRecommendation(
          id:          'hearing_ent_referral',
          title:       'ENT Specialist Referral',
          description: 'Refer to ear, nose and throat specialist for '
              'detailed assessment and hearing rehabilitation plan.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.referral,
          triggerType: DisabilityType.hearing,
        ),
        const PwdRecommendation(
          id:          'hearing_provider_note',
          title:       'Provider Note: Communication Adjustment',
          description: 'Patient has a hearing impairment. Face the patient '
              'when speaking. Speak clearly and at normal pace (do not shout). '
              'Offer written summaries of key instructions. '
              'Ask patient if they lip-read or prefer sign language interpreter.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.providerNote,
          triggerType: DisabilityType.hearing,
        ),
      ];

  // ----------------------------------------------------------
  // Mobility / Physical disability rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _mobilityRules(DisabilityProfile profile) {
    final isWheelchair = profile.assistiveDevices
        .any((d) => d.toLowerCase().contains('wheelchair'));
    final usesCatheter = profile.assistiveDevices
        .any((d) => d.toLowerCase().contains('catheter'));

    return [
      PwdRecommendation(
        id:          'mobility_pressure_sore',
        title:       'Pressure Sore / Decubitus Ulcer Assessment',
        description: 'Examine all bony pressure points (sacrum, heels, '
            'ischial tuberosities) for skin breakdown. '
            '${isWheelchair ? "Wheelchair users are at high risk — assess at every visit." : "Assess if patient has reduced mobility."}',
        priority:    isWheelchair
            ? RecommendationPriority.critical
            : RecommendationPriority.high,
        category:    RecommendationCategory.healthCheck,
        triggerType: DisabilityType.mobility,
      ),
      const PwdRecommendation(
        id:          'mobility_dvt',
        title:       'DVT Risk Assessment',
        description: 'Deep vein thrombosis risk is elevated in patients '
            'with limited mobility. Assess for leg swelling, redness, or '
            'pain. Consider prophylactic measures for high-risk patients.',
        priority:    RecommendationPriority.high,
        category:    RecommendationCategory.healthCheck,
        triggerType: DisabilityType.mobility,
      ),
      const PwdRecommendation(
        id:          'mobility_physio_referral',
        title:       'Physiotherapy Referral',
        description: 'Regular physiotherapy helps maintain function, '
            'prevent contractures, manage spasticity, and improve '
            'independence. Refer to physiotherapist.',
        priority:    RecommendationPriority.high,
        category:    RecommendationCategory.referral,
        triggerType: DisabilityType.mobility,
        actionLabel: 'Refer to physiotherapist',
      ),
      const PwdRecommendation(
        id:          'mobility_bone_density',
        title:       'Bone Density Scan (DEXA)',
        description: 'Reduced physical activity leads to decreased bone '
            'density and increased fracture risk. Recommend DEXA scan '
            'annually for patients with moderate or severe mobility impairment.',
        priority:    RecommendationPriority.medium,
        category:    RecommendationCategory.labTest,
        triggerType: DisabilityType.mobility,
      ),
      const PwdRecommendation(
        id:          'mobility_cardiovascular',
        title:       'Cardiovascular Health Assessment',
        description: 'Sedentary lifestyle increases cardiovascular risk. '
            'Assess lipid profile, blood pressure, and BMI. '
            'Recommend adapted exercise where possible.',
        priority:    RecommendationPriority.medium,
        category:    RecommendationCategory.healthCheck,
        triggerType: DisabilityType.mobility,
      ),
      if (usesCatheter)
        const PwdRecommendation(
          id:          'mobility_uti_screening',
          title:       'UTI Screening (Catheter User)',
          description: 'Catheter use significantly increases UTI risk. '
              'Screen urine at every visit. Educate on catheter hygiene. '
              'Consider intermittent catheterisation if appropriate.',
          priority:    RecommendationPriority.critical,
          category:    RecommendationCategory.labTest,
          triggerType: DisabilityType.mobility,
        ),
      const PwdRecommendation(
        id:          'mobility_provider_note',
        title:       'Provider Note: Physical Accessibility',
        description: 'Patient has a mobility impairment. '
            'Ensure examination room is wheelchair accessible. '
            'Allow extra time for transfers to examination table. '
            'Offer adjustable-height examination table if available. '
            'Document any positioning limitations before physical examination.',
        priority:    RecommendationPriority.high,
        category:    RecommendationCategory.providerNote,
        triggerType: DisabilityType.mobility,
      ),
    ];
  }

  // ----------------------------------------------------------
  // Cognitive / Intellectual disability rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _cognitiveRules(DisabilityProfile profile) => [
        PwdRecommendation(
          id:          'cognitive_caregiver_required',
          title:       'Caregiver / Guardian Required',
          description: profile.requiresCaregiverForConsent
              ? 'Provider has assessed that a caregiver or legal guardian '
                  'must be present for informed consent and medical decisions.'
              : 'Consider whether a caregiver or legal guardian needs to be '
                  'involved in medical decision-making.',
          priority:    profile.requiresCaregiverForConsent
              ? RecommendationPriority.critical
              : RecommendationPriority.high,
          category:    RecommendationCategory.caregiverAlert,
          triggerType: DisabilityType.cognitive,
        ),
        const PwdRecommendation(
          id:          'cognitive_mental_state',
          title:       'Mental State Assessment',
          description: 'Use standardised tool (Mini-Mental State Examination '
              'or equivalent) to track cognitive function. Compare with '
              'baseline at each visit.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.cognitive,
        ),
        const PwdRecommendation(
          id:          'cognitive_medication_support',
          title:       'Medication Adherence Support',
          description: 'Patients with cognitive disability often need '
              'structured support for medication adherence. '
              'Consider pill organisers, carer reminders, or simplified '
              'dosing schedules. Involve caregiver.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.medication,
          triggerType: DisabilityType.cognitive,
        ),
        const PwdRecommendation(
          id:          'cognitive_dental',
          title:       'Dental Health Check',
          description: 'Oral health is frequently neglected in patients '
              'with cognitive disability. Refer to dentist annually. '
              'Assess ability to self-clean teeth.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.referral,
          triggerType: DisabilityType.cognitive,
        ),
        const PwdRecommendation(
          id:          'cognitive_nutrition',
          title:       'Nutritional Assessment',
          description: 'Assess dietary intake, weight trends, and swallowing '
              'ability. Refer to dietitian if underweight or if swallowing '
              'difficulties are present.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.cognitive,
        ),
        const PwdRecommendation(
          id:          'cognitive_seizure',
          title:       'Seizure Risk Assessment',
          description: 'Epilepsy occurs at higher rates in people with '
              'cognitive disability. Ask about seizure history and ensure '
              'appropriate management if present.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.cognitive,
        ),
        const PwdRecommendation(
          id:          'cognitive_provider_note',
          title:       'Provider Note: Consultation Approach',
          description: 'Patient has a cognitive / intellectual disability. '
              'Use simple, clear language — one instruction at a time. '
              'Allow extra time; do not rush. '
              'Confirm understanding by asking the patient to repeat back. '
              'Caregiver or legal guardian consent may be required. '
              'Document capacity assessment in notes.',
          priority:    RecommendationPriority.critical,
          category:    RecommendationCategory.providerNote,
          triggerType: DisabilityType.cognitive,
        ),
      ];

  // ----------------------------------------------------------
  // Speech / Communication impairment rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _speechRules(DisabilityProfile profile) => [
        const PwdRecommendation(
          id:          'speech_therapist_referral',
          title:       'Speech-Language Therapist Referral',
          description: 'Refer to speech-language therapist for '
              'communication assessment, AAC device training, and '
              'ongoing therapy.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.referral,
          triggerType: DisabilityType.speech,
          actionLabel: 'Refer to SLT',
        ),
        const PwdRecommendation(
          id:          'speech_aac_check',
          title:       'AAC Device / Communication Aid Check',
          description: 'Confirm patient\'s communication device (if used) '
              'is functional and that patient/carer know how to use it. '
              'Refer to AAC specialist if upgrade needed.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.lifestyle,
          triggerType: DisabilityType.speech,
        ),
        const PwdRecommendation(
          id:          'speech_mental_health',
          title:       'Mental Health Screening',
          description: 'Speech impairment is associated with frustration, '
              'social isolation, and depression. Screen using PHQ-9 or '
              'equivalent. Refer to psychologist if needed.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.speech,
        ),
        const PwdRecommendation(
          id:          'speech_swallowing',
          title:       'Swallowing / Dysphagia Assessment',
          description: 'Speech impairment is sometimes accompanied by '
              'dysphagia (swallowing difficulty). Assess for choking risk '
              'and aspiration. Refer to SLT if dysphagia is suspected.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.speech,
        ),
        const PwdRecommendation(
          id:          'speech_provider_note',
          title:       'Provider Note: Communication Approach',
          description: 'Patient has a speech or communication impairment. '
              'Allow extra time for responses — do not complete sentences. '
              'Patient may use written communication, AAC device, or '
              'gestures. Ask the patient\'s preferred method at the start. '
              'Do not assume cognitive impairment based on speech alone.',
          priority:    RecommendationPriority.critical,
          category:    RecommendationCategory.providerNote,
          triggerType: DisabilityType.speech,
        ),
      ];

  // ----------------------------------------------------------
  // Chronic illness rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _chronicIllnessRules(DisabilityProfile profile) => [
        const PwdRecommendation(
          id:          'chronic_bp_monitoring',
          title:       'Blood Pressure Monitoring',
          description: 'Blood pressure should be checked at every visit. '
              'Target < 130/80 mmHg for most patients with chronic illness.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.chronicIllness,
        ),
        const PwdRecommendation(
          id:          'chronic_hba1c',
          title:       'HbA1c Test (Every 3 Months)',
          description: 'For patients with diabetes or pre-diabetes. '
              'Target HbA1c < 7% for most patients. Adjust medications '
              'based on result.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.labTest,
          triggerType: DisabilityType.chronicIllness,
          actionLabel: 'Order HbA1c',
        ),
        const PwdRecommendation(
          id:          'chronic_kidney_function',
          title:       'Kidney Function Tests',
          description: 'eGFR, serum creatinine, and urine protein-to-'
              'creatinine ratio. Annual minimum; more frequent if eGFR < 60.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.labTest,
          triggerType: DisabilityType.chronicIllness,
        ),
        const PwdRecommendation(
          id:          'chronic_foot_exam',
          title:       'Foot Examination',
          description: 'Annual foot inspection for neuropathy, ulcers, '
              'and circulation problems. At-risk patients (previous ulcer, '
              'neuropathy, poor circulation) should be seen every 3 months.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.chronicIllness,
        ),
        const PwdRecommendation(
          id:          'chronic_eye_exam',
          title:       'Diabetic Eye Examination',
          description: 'Annual dilated fundus examination to detect '
              'diabetic retinopathy early. Refer to ophthalmologist.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.chronicIllness,
          actionLabel: 'Refer to ophthalmologist',
        ),
        const PwdRecommendation(
          id:          'chronic_medication_adherence',
          title:       'Medication Adherence Review',
          description: 'Review all current medications at every visit. '
              'Ask about missed doses, side effects, and cost barriers. '
              'Simplify regimen where possible.',
          priority:    RecommendationPriority.high,
          category:    RecommendationCategory.medication,
          triggerType: DisabilityType.chronicIllness,
        ),
        const PwdRecommendation(
          id:          'chronic_lipid_profile',
          title:       'Lipid Profile',
          description: 'Fasting lipid panel annually. '
              'Cardiovascular risk is elevated in most chronic illnesses.',
          priority:    RecommendationPriority.medium,
          category:    RecommendationCategory.labTest,
          triggerType: DisabilityType.chronicIllness,
        ),
      ];

  // ----------------------------------------------------------
  // Mental health rules
  // ----------------------------------------------------------
  List<PwdRecommendation> _mentalHealthRules(DisabilityProfile profile) {
    final isSevere = profile.severity == DisabilitySeverity.severe;

    return [
      const PwdRecommendation(
        id:          'mental_monthly_assessment',
        title:       'Monthly Mental Health Assessment',
        description: 'Regular structured assessment of mood, anxiety, '
            'sleep, and functioning. Use PHQ-9 for depression and '
            'GAD-7 for anxiety at minimum.',
        priority:    RecommendationPriority.high,
        category:    RecommendationCategory.healthCheck,
        triggerType: DisabilityType.mentalHealth,
      ),
      const PwdRecommendation(
        id:          'mental_medication_adherence',
        title:       'Psychiatric Medication Adherence',
        description: 'Review all psychiatric medications at every visit. '
            'Ask about missed doses and side effects. '
            'Stopping medication abruptly is dangerous — educate patient.',
        priority:    RecommendationPriority.high,
        category:    RecommendationCategory.medication,
        triggerType: DisabilityType.mentalHealth,
      ),
      const PwdRecommendation(
        id:          'mental_sleep',
        title:       'Sleep Quality Assessment',
        description: 'Poor sleep significantly worsens mental health. '
            'Use Pittsburgh Sleep Quality Index or ask structured questions '
            'about sleep duration, quality, and daytime sleepiness.',
        priority:    RecommendationPriority.medium,
        category:    RecommendationCategory.healthCheck,
        triggerType: DisabilityType.mentalHealth,
      ),
      const PwdRecommendation(
        id:          'mental_social_support',
        title:       'Social Support Network Assessment',
        description: 'Isolation worsens mental health outcomes. '
            'Assess patient\'s support network. '
            'Refer to social worker or community support group if isolated.',
        priority:    RecommendationPriority.medium,
        category:    RecommendationCategory.lifestyle,
        triggerType: DisabilityType.mentalHealth,
      ),
      const PwdRecommendation(
        id:          'mental_psychiatrist_referral',
        title:       'Psychiatrist Referral',
        description: 'For complex or treatment-resistant cases, refer '
            'to psychiatrist for specialist assessment and management.',
        priority:    RecommendationPriority.medium,
        category:    RecommendationCategory.referral,
        triggerType: DisabilityType.mentalHealth,
      ),
      if (isSevere)
        const PwdRecommendation(
          id:          'mental_suicide_risk',
          title:       'Suicide Risk Screening',
          description: 'REQUIRED for severe mental health conditions. '
              'Use a validated tool (Columbia Suicide Severity Rating Scale). '
              'Document risk level. Have a safety plan discussion.',
          priority:    RecommendationPriority.critical,
          category:    RecommendationCategory.healthCheck,
          triggerType: DisabilityType.mentalHealth,
        ),
      const PwdRecommendation(
        id:          'mental_provider_note',
        title:       'Provider Note: Consultation Environment',
        description: 'Patient has a mental health condition. '
            'Ensure a private, calm, and non-judgmental consultation space. '
            'Use non-stigmatising language. '
            'Avoid expressions like "crazy" or "mad". '
            'Confirm the patient feels safe before beginning. '
            'Ask about current support system.',
        priority:    RecommendationPriority.high,
        category:    RecommendationCategory.providerNote,
        triggerType: DisabilityType.mentalHealth,
      ),
    ];
  }
}
